import { createFileRoute } from "@tanstack/react-router";
import { Pool, type PoolClient } from "pg";

const ADMIN_EMAIL = "lacviet55@proton.me";
const CODE = /^[A-Z2-9]{6}$/;
const schema = `
create table if not exists public.watch_parties (
  id uuid primary key default gen_random_uuid(), code text not null unique,
  host_id uuid not null references auth.users(id) on delete cascade,
  slug text not null, source text not null default 'kkphim', name text not null, poster text,
  ep_index integer not null default 0, srv_index integer not null default 0,
  position_seconds double precision not null default 0, is_playing boolean not null default false,
  closed boolean not null default false, join_locked boolean not null default false,
  chat_mode text not null default 'all' check(chat_mode in ('all','host')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.watch_parties add column if not exists join_locked boolean not null default false;
create table if not exists public.watch_party_messages (
  id uuid primary key default gen_random_uuid(), party_id uuid not null references public.watch_parties(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade, display_name text,
  content text not null check(char_length(content) between 1 and 500),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.watch_party_members (
  id uuid primary key default gen_random_uuid(), party_id uuid not null references public.watch_parties(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade, created_at timestamptz not null default now(), unique(party_id,user_id)
);
create table if not exists public.watch_party_warnings (
  id uuid primary key default gen_random_uuid(), party_id uuid not null references public.watch_parties(id) on delete cascade,
  actor_id uuid not null references auth.users(id) on delete restrict,
  message text not null check(char_length(message) between 1 and 300), created_at timestamptz not null default now()
);
create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key, actor_id uuid not null references auth.users(id) on delete restrict,
  action text not null, target_type text not null, target_id text not null,
  details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create table if not exists public.staff_permissions (
  user_id uuid not null references auth.users(id) on delete cascade,
  permission text not null check(permission in ('users.view','users.manage','comments.view','comments.moderate','watch_party.view','watch_party.warn','watch_party.lock','watch_party.close','sources.view')),
  granted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(), primary key(user_id,permission)
);
alter table public.staff_permissions add column if not exists granted_by uuid references auth.users(id) on delete set null;
alter table public.watch_parties enable row level security;
alter table public.watch_party_messages enable row level security;
alter table public.watch_party_members enable row level security;
revoke insert,update,delete on public.watch_parties,public.watch_party_messages,public.watch_party_members from authenticated;
grant select on public.watch_parties,public.watch_party_messages,public.watch_party_members to authenticated;
drop policy if exists "Authenticated can view open parties" on public.watch_parties;
drop policy if exists "Party members view parties" on public.watch_parties;
create policy "Party members view parties" on public.watch_parties for select to authenticated using (
  host_id=auth.uid() or exists(select 1 from public.watch_party_members m where m.party_id=watch_parties.id and m.user_id=auth.uid())
);
drop policy if exists "Authenticated can read party messages" on public.watch_party_messages;
drop policy if exists "Party members view messages" on public.watch_party_messages;
create policy "Party members view messages" on public.watch_party_messages for select to authenticated using (
  exists(select 1 from public.watch_party_members m where m.party_id=watch_party_messages.party_id and m.user_id=auth.uid())
);
`;

let pool: Pool | undefined;
let schemaReady = false;
function db() {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) throw new Error("DATABASE_URL is required");
  return (pool ??= new Pool({ connectionString, ssl: { rejectUnauthorized: false }, max: 2 }));
}
async function ensureSchema() {
  if (schemaReady) return;
  await db().query(schema);
  schemaReady = true;
}
type CurrentUser = { id: string; email?: string; role?: string };
async function currentUser(request: Request): Promise<CurrentUser | null> {
  const token = request.headers.get("authorization")?.replace(/^Bearer\s+/i, "");
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY;
  if (!token || !url || !key) return null;
  const response = await fetch(`${url}/auth/v1/user`, {
    headers: { apikey: key, authorization: `Bearer ${token}` },
  });
  if (!response.ok) return null;
  const user = (await response.json()) as {
    id?: string;
    email?: string;
    app_metadata?: { role?: string };
  };
  return user.id ? { id: user.id, email: user.email, role: user.app_metadata?.role } : null;
}
const isAdmin = (user: CurrentUser) => user.email?.toLowerCase() === ADMIN_EMAIL;
async function hasPermission(user: CurrentUser, permission: string) {
  if (isAdmin(user)) return true;
  if (user.role !== "deputy_admin") return false;
  const result = await db().query(
    `select 1 from public.staff_permissions where user_id=$1 and permission=$2`,
    [user.id, permission],
  );
  return !!result.rowCount;
}
const text = (value: unknown, max: number) => {
  const result = typeof value === "string" ? value.trim() : "";
  return result && result.length <= max ? result : null;
};
const integer = (value: unknown) => {
  const result = Number(value);
  return Number.isInteger(result) && result >= 0 ? result : null;
};
const json = (data: unknown, status = 200) =>
  Response.json(data, { status, headers: { "cache-control": "no-store" } });
async function memberOrStaff(user: CurrentUser, partyId: string, permission = "watch_party.view") {
  if (await hasPermission(user, permission)) return true;
  const result = await db().query(
    `select 1 from public.watch_parties p left join public.watch_party_members m on m.party_id=p.id and m.user_id=$2
     where p.id=$1 and (p.host_id=$2 or m.user_id=$2)`,
    [partyId, user.id],
  );
  return !!result.rowCount;
}
async function audit(
  client: PoolClient,
  user: CurrentUser,
  action: string,
  partyId: string,
  details: Record<string, unknown> = {},
) {
  await client.query(
    `insert into public.admin_audit_log(actor_id,action,target_type,target_id,details)
     values($1,$2,'watch_party',$3,$4::jsonb)`,
    [user.id, action, partyId, JSON.stringify(details)],
  );
}

async function createParty(user: CurrentUser, body: Record<string, unknown>) {
  const code = String(body.code ?? "")
    .trim()
    .toUpperCase();
  const slug = text(body.slug, 300);
  const source = text(body.source, 30);
  const name = text(body.name, 300);
  const ep = integer(body.ep) ?? 0;
  const srv = integer(body.srv) ?? 0;
  if (!CODE.test(code) || !slug || !source || !name)
    return json({ error: "Dữ liệu phòng không hợp lệ" }, 400);
  const client = await db().connect();
  try {
    await client.query("begin");
    const { rows } = await client.query(
      `insert into public.watch_parties(code,host_id,slug,source,name,poster,ep_index,srv_index)
       values($1,$2,$3,$4,$5,$6,$7,$8) returning *`,
      [code, user.id, slug, source, name, text(body.poster, 1000), ep, srv],
    );
    await client.query(
      `insert into public.watch_party_members(party_id,user_id) values($1,$2) on conflict(party_id,user_id) do nothing`,
      [rows[0].id, user.id],
    );
    await client.query("commit");
    return json({ party: rows[0] });
  } catch (error) {
    await client.query("rollback");
    throw error;
  } finally {
    client.release();
  }
}

async function joinParty(user: CurrentUser, body: Record<string, unknown>) {
  const code = String(body.code ?? "")
    .trim()
    .toUpperCase();
  if (!CODE.test(code)) return json({ error: "Mã phòng không hợp lệ" }, 400);
  const client = await db().connect();
  try {
    await client.query("begin");
    const partyResult = await client.query(
      `select * from public.watch_parties where code=$1 and closed=false for update`,
      [code],
    );
    const party = partyResult.rows[0];
    if (!party) {
      await client.query("rollback");
      return json({ party: null });
    }
    const member = await client.query(
      `select 1 from public.watch_party_members where party_id=$1 and user_id=$2`,
      [party.id, user.id],
    );
    if (party.join_locked && party.host_id !== user.id && !member.rowCount && !isAdmin(user)) {
      await client.query("rollback");
      return json({ error: "Phòng đang khóa người tham gia mới" }, 403);
    }
    await client.query(
      `insert into public.watch_party_members(party_id,user_id) values($1,$2) on conflict(party_id,user_id) do nothing`,
      [party.id, user.id],
    );
    await client.query("commit");
    return json({ party });
  } catch (error) {
    await client.query("rollback");
    throw error;
  } finally {
    client.release();
  }
}

async function transferHost(user: CurrentUser, partyId: string, targetId: string) {
  if (!partyId || !targetId || targetId === user.id)
    return json({ error: "Thành viên không hợp lệ" }, 400);
  const client = await db().connect();
  try {
    await client.query("begin");
    const party = await client.query(
      `select id,host_id from public.watch_parties where id=$1 and closed=false for update`,
      [partyId],
    );
    if (!party.rowCount) {
      await client.query("rollback");
      return json({ error: "Phòng không tồn tại hoặc đã đóng" }, 404);
    }
    if (party.rows[0].host_id !== user.id) {
      await client.query("rollback");
      return json({ error: "Chỉ chủ phòng được chuyển chủ" }, 403);
    }
    const target = await client.query(
      `select 1 from public.watch_party_members where party_id=$1 and user_id=$2`,
      [partyId, targetId],
    );
    if (!target.rowCount) {
      await client.query("rollback");
      return json({ error: "Người nhận phải là thành viên phòng" }, 400);
    }
    await client.query(`update public.watch_parties set host_id=$2,updated_at=now() where id=$1`, [
      partyId,
      targetId,
    ]);
    await audit(client, user, "watch_party.transfer_host", partyId, {
      old_host_id: user.id,
      new_host_id: targetId,
    });
    await client.query("commit");
    return json({ ok: true });
  } catch (error) {
    await client.query("rollback");
    throw error;
  } finally {
    client.release();
  }
}

async function handler(request: Request) {
  try {
    const user = await currentUser(request);
    if (!user) return json({ error: "Unauthorized" }, 401);
    await ensureSchema();
    const body = (await request.json()) as Record<string, unknown>;
    if (body.action === "create") return createParty(user, body);
    if (body.action === "join") return joinParty(user, body);
    const partyId = String(body.partyId ?? "");

    if (body.action === "members-list") {
      if (!(await memberOrStaff(user, partyId))) return json({ error: "Forbidden" }, 403);
      const { rows } = await db().query(
        `select m.user_id,coalesce(p.display_name,u.raw_user_meta_data->>'display_name',split_part(u.email,'@',1)) as display_name,
                m.created_at as joined_at
         from public.watch_party_members m left join public.profiles p on p.id=m.user_id
         left join auth.users u on u.id=m.user_id where m.party_id=$1 order by m.created_at`,
        [partyId],
      );
      return json({ members: rows });
    }
    if (body.action === "warnings-list") {
      if (!(await memberOrStaff(user, partyId))) return json({ error: "Forbidden" }, 403);
      const { rows } = await db().query(
        `select id,party_id,message,created_at from public.watch_party_warnings where party_id=$1 order by created_at desc limit 10`,
        [partyId],
      );
      return json({ warnings: rows });
    }
    if (body.action === "chat-list") {
      if (!(await memberOrStaff(user, partyId))) return json({ error: "Forbidden" }, 403);
      const { rows } = await db().query(
        `select wm.id,wm.party_id,wm.user_id,wm.display_name,wm.content,wm.created_at,
                case when lower(u.email)=$2 then 'admin'
                     when u.raw_app_meta_data->>'role'='deputy_admin' then 'deputy_admin'
                     else 'member' end as staff_role
         from public.watch_party_messages wm join auth.users u on u.id=wm.user_id
         where wm.party_id=$1 order by wm.created_at asc limit 200`,
        [partyId, ADMIN_EMAIL],
      );
      return json({ messages: rows });
    }
    if (body.action === "chat-send") {
      const content = String(body.content ?? "").trim();
      if (!content || content.length > 500) return json({ error: "Tin nhắn không hợp lệ" }, 400);
      const { rows } = await db().query(
        `insert into public.watch_party_messages(party_id,user_id,display_name,content)
         select p.id,$2,
           case when lower(u.email)=$4 then 'Nhím Admin'
                when u.raw_app_meta_data->>'role'='deputy_admin'
                  then 'Phó Admin Lạc Việt · ' || coalesce(pr.display_name,u.raw_user_meta_data->>'display_name',split_part(u.email,'@',1),'Thành viên')
                else coalesce(pr.display_name,u.raw_user_meta_data->>'display_name',split_part(u.email,'@',1),'Thành viên') end,
           $3
         from public.watch_parties p
         join public.watch_party_members m on m.party_id=p.id and m.user_id=$2
         join auth.users u on u.id=$2
         left join public.profiles pr on pr.id=$2
         where p.id=$1 and p.closed=false and (p.chat_mode='all' or p.host_id=$2)
         returning *`,
        [partyId, user.id, content, ADMIN_EMAIL],
      );
      if (!rows[0]) return json({ error: "Phòng đã đóng hoặc chat đang bị khoá" }, 403);
      return json({ message: rows[0] });
    }
    if (body.action === "close") {
      const admin = isAdmin(user) || (await hasPermission(user, "watch_party.close"));
      const client = await db().connect();
      try {
        await client.query("begin");
        const { rows } = await client.query(
          `update public.watch_parties set closed=true,updated_at=now()
           where id=$1 and closed=false and (host_id=$2 or $3) returning code`,
          [partyId, user.id, admin],
        );
        if (!rows[0]) {
          await client.query("rollback");
          return json({ error: "Chỉ chủ phòng hoặc Admin được đóng phòng" }, 403);
        }
        await audit(
          client,
          user,
          admin ? "watch_party.admin_close" : "watch_party.host_close",
          partyId,
        );
        await client.query("commit");
        return json({ code: rows[0].code });
      } catch (error) {
        await client.query("rollback");
        throw error;
      } finally {
        client.release();
      }
    }
    if (body.action === "set-lock") {
      if (typeof body.locked !== "boolean")
        return json({ error: "Trạng thái khóa không hợp lệ" }, 400);
      const client = await db().connect();
      try {
        await client.query("begin");
        const { rows } = await client.query(
          `update public.watch_parties set join_locked=$3,updated_at=now()
           where id=$1 and host_id=$2 and closed=false returning id`,
          [partyId, user.id, body.locked],
        );
        if (!rows[0]) {
          await client.query("rollback");
          return json({ error: "Chỉ chủ phòng được khóa phòng" }, 403);
        }
        await audit(client, user, "watch_party.set_lock", partyId, { join_locked: body.locked });
        await client.query("commit");
        return json({ ok: true });
      } catch (error) {
        await client.query("rollback");
        throw error;
      } finally {
        client.release();
      }
    }
    if (body.action === "transfer-host")
      return transferHost(user, partyId, String(body.userId ?? ""));
    if (body.action === "sync") {
      const input = (body.patch ?? {}) as Record<string, unknown>;
      const patch: Record<string, unknown> = {};
      for (const key of ["ep_index", "srv_index"])
        if (integer(input[key]) !== null) patch[key] = integer(input[key]);
      if (
        typeof input.position_seconds === "number" &&
        Number.isFinite(input.position_seconds) &&
        input.position_seconds >= 0
      )
        patch.position_seconds = input.position_seconds;
      if (typeof input.is_playing === "boolean") patch.is_playing = input.is_playing;
      if (input.chat_mode === "all" || input.chat_mode === "host")
        patch.chat_mode = input.chat_mode;
      const entries = Object.entries(patch);
      if (!entries.length) return json({ error: "Không có thay đổi hợp lệ" }, 400);
      const sets = entries.map(([key], index) => `${key}=$${index + 3}`).join(",");
      const { rows } = await db().query(
        `update public.watch_parties set ${sets},updated_at=now() where id=$1 and host_id=$2 and closed=false returning *`,
        [partyId, user.id, ...entries.map(([, value]) => value)],
      );
      if (!rows[0]) return json({ error: "Chỉ chủ phòng được điều khiển" }, 403);
      return json({ party: rows[0] });
    }
    return json({ error: "Unknown action" }, 400);
  } catch (error) {
    console.error("[watch-party]", error);
    return json({ error: "Server error" }, 500);
  }
}

export const Route = createFileRoute("/api/watch-party")({
  server: { handlers: { POST: ({ request }) => handler(request) } },
});
