/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ActorRouteImport } from './routes/actor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiActorRouteImport } from './routes/api/actor'
import { Route as ApiAdminRouteImport } from './routes/api/admin'
import { Route as ApiEpisodeWatcherRouteImport } from './routes/api/episode-watcher'
import { Route as ApiMovieMetadataRouteImport } from './routes/api/movie-metadata'
import { Route as ApiPromocodeRouteImport } from './routes/api/promocode'
import { Route as ApiRatingsRouteImport } from './routes/api/ratings'
import { Route as ApiWatchHistoryRouteImport } from './routes/api/watch-history'
import { Route as ApiWatchPartyRouteImport } from './routes/api/watch-party'
import { Route as MovieSlugRouteImport } from './routes/movie.$slug'
import { Route as WatchSlugRouteImport } from './routes/watch.$slug'
import { Route as ApiPublicVsmovStreamRouteImport } from './routes/api/public/vsmov-stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorRoute = ActorRouteImport.update({
  id: '/actor',
  path: '/actor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActorRoute = ApiActorRouteImport.update({
  id: '/api/actor',
  path: '/api/actor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEpisodeWatcherRoute = ApiEpisodeWatcherRouteImport.update({
  id: '/api/episode-watcher',
  path: '/api/episode-watcher',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMovieMetadataRoute = ApiMovieMetadataRouteImport.update({
  id: '/api/movie-metadata',
  path: '/api/movie-metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromocodeRoute = ApiPromocodeRouteImport.update({
  id: '/api/promocode',
  path: '/api/promocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRatingsRoute = ApiRatingsRouteImport.update({
  id: '/api/ratings',
  path: '/api/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchHistoryRoute = ApiWatchHistoryRouteImport.update({
  id: '/api/watch-history',
  path: '/api/watch-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchPartyRoute = ApiWatchPartyRouteImport.update({
  id: '/api/watch-party',
  path: '/api/watch-party',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieSlugRoute = MovieSlugRouteImport.update({
  id: '/movie/$slug',
  path: '/movie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchSlugRoute = WatchSlugRouteImport.update({
  id: '/watch/$slug',
  path: '/watch/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVsmovStreamRoute = ApiPublicVsmovStreamRouteImport.update({
  id: '/api/public/vsmov-stream',
  path: '/api/public/vsmov-stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/actor': typeof ActorRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/actor': typeof ApiActorRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/episode-watcher': typeof ApiEpisodeWatcherRoute
  '/api/movie-metadata': typeof ApiMovieMetadataRoute
  '/api/promocode': typeof ApiPromocodeRoute
  '/api/ratings': typeof ApiRatingsRoute
  '/api/watch-history': typeof ApiWatchHistoryRoute
  '/api/watch-party': typeof ApiWatchPartyRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/api/public/vsmov-stream': typeof ApiPublicVsmovStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/actor': typeof ActorRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/actor': typeof ApiActorRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/episode-watcher': typeof ApiEpisodeWatcherRoute
  '/api/movie-metadata': typeof ApiMovieMetadataRoute
  '/api/promocode': typeof ApiPromocodeRoute
  '/api/ratings': typeof ApiRatingsRoute
  '/api/watch-history': typeof ApiWatchHistoryRoute
  '/api/watch-party': typeof ApiWatchPartyRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/api/public/vsmov-stream': typeof ApiPublicVsmovStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/actor': typeof ActorRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/actor': typeof ApiActorRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/episode-watcher': typeof ApiEpisodeWatcherRoute
  '/api/movie-metadata': typeof ApiMovieMetadataRoute
  '/api/promocode': typeof ApiPromocodeRoute
  '/api/ratings': typeof ApiRatingsRoute
  '/api/watch-history': typeof ApiWatchHistoryRoute
  '/api/watch-party': typeof ApiWatchPartyRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/api/public/vsmov-stream': typeof ApiPublicVsmovStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/actor'
    | '/admin'
    | '/auth'
    | '/legal'
    | '/search'
    | '/settings'
    | '/api/actor'
    | '/api/admin'
    | '/api/episode-watcher'
    | '/api/movie-metadata'
    | '/api/promocode'
    | '/api/ratings'
    | '/api/watch-history'
    | '/api/watch-party'
    | '/movie/$slug'
    | '/watch/$slug'
    | '/api/public/vsmov-stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/actor'
    | '/admin'
    | '/auth'
    | '/legal'
    | '/search'
    | '/settings'
    | '/api/actor'
    | '/api/admin'
    | '/api/episode-watcher'
    | '/api/movie-metadata'
    | '/api/promocode'
    | '/api/ratings'
    | '/api/watch-history'
    | '/api/watch-party'
    | '/movie/$slug'
    | '/watch/$slug'
    | '/api/public/vsmov-stream'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/actor'
    | '/admin'
    | '/auth'
    | '/legal'
    | '/search'
    | '/settings'
    | '/api/actor'
    | '/api/admin'
    | '/api/episode-watcher'
    | '/api/movie-metadata'
    | '/api/promocode'
    | '/api/ratings'
    | '/api/watch-history'
    | '/api/watch-party'
    | '/movie/$slug'
    | '/watch/$slug'
    | '/api/public/vsmov-stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ActorRoute: typeof ActorRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  LegalRoute: typeof LegalRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ApiActorRoute: typeof ApiActorRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiEpisodeWatcherRoute: typeof ApiEpisodeWatcherRoute
  ApiMovieMetadataRoute: typeof ApiMovieMetadataRoute
  ApiPromocodeRoute: typeof ApiPromocodeRoute
  ApiRatingsRoute: typeof ApiRatingsRoute
  ApiWatchHistoryRoute: typeof ApiWatchHistoryRoute
  ApiWatchPartyRoute: typeof ApiWatchPartyRoute
  MovieSlugRoute: typeof MovieSlugRoute
  WatchSlugRoute: typeof WatchSlugRoute
  ApiPublicVsmovStreamRoute: typeof ApiPublicVsmovStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actor': {
      id: '/actor'
      path: '/actor'
      fullPath: '/actor'
      preLoaderRoute: typeof ActorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/actor': {
      id: '/api/actor'
      path: '/api/actor'
      fullPath: '/api/actor'
      preLoaderRoute: typeof ApiActorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/episode-watcher': {
      id: '/api/episode-watcher'
      path: '/api/episode-watcher'
      fullPath: '/api/episode-watcher'
      preLoaderRoute: typeof ApiEpisodeWatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/movie-metadata': {
      id: '/api/movie-metadata'
      path: '/api/movie-metadata'
      fullPath: '/api/movie-metadata'
      preLoaderRoute: typeof ApiMovieMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/promocode': {
      id: '/api/promocode'
      path: '/api/promocode'
      fullPath: '/api/promocode'
      preLoaderRoute: typeof ApiPromocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ratings': {
      id: '/api/ratings'
      path: '/api/ratings'
      fullPath: '/api/ratings'
      preLoaderRoute: typeof ApiRatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watch-history': {
      id: '/api/watch-history'
      path: '/api/watch-history'
      fullPath: '/api/watch-history'
      preLoaderRoute: typeof ApiWatchHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watch-party': {
      id: '/api/watch-party'
      path: '/api/watch-party'
      fullPath: '/api/watch-party'
      preLoaderRoute: typeof ApiWatchPartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$slug': {
      id: '/movie/$slug'
      path: '/movie/$slug'
      fullPath: '/movie/$slug'
      preLoaderRoute: typeof MovieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$slug': {
      id: '/watch/$slug'
      path: '/watch/$slug'
      fullPath: '/watch/$slug'
      preLoaderRoute: typeof WatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vsmov-stream': {
      id: '/api/public/vsmov-stream'
      path: '/api/public/vsmov-stream'
      fullPath: '/api/public/vsmov-stream'
      preLoaderRoute: typeof ApiPublicVsmovStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ActorRoute: ActorRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  LegalRoute: LegalRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ApiActorRoute: ApiActorRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiEpisodeWatcherRoute: ApiEpisodeWatcherRoute,
  ApiMovieMetadataRoute: ApiMovieMetadataRoute,
  ApiPromocodeRoute: ApiPromocodeRoute,
  ApiRatingsRoute: ApiRatingsRoute,
  ApiWatchHistoryRoute: ApiWatchHistoryRoute,
  ApiWatchPartyRoute: ApiWatchPartyRoute,
  MovieSlugRoute: MovieSlugRoute,
  WatchSlugRoute: WatchSlugRoute,
  ApiPublicVsmovStreamRoute: ApiPublicVsmovStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
