/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiAdminRouteImport } from './routes/api/admin'
import { Route as ApiEpisodeWatcherRouteImport } from './routes/api/episode-watcher'
import { Route as ApiRatingsRouteImport } from './routes/api/ratings'
import { Route as ApiWatchHistoryRouteImport } from './routes/api/watch-history'
import { Route as ApiWatchPartyRouteImport } from './routes/api/watch-party'
import { Route as MovieSlugRouteImport } from './routes/movie.$slug'
import { Route as WatchSlugRouteImport } from './routes/watch.$slug'
import { Route as ApiPublicVsmovStreamRouteImport } from './routes/api/public/vsmov-stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEpisodeWatcherRoute = ApiEpisodeWatcherRouteImport.update({
  id: '/api/episode-watcher',
  path: '/api/episode-watcher',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRatingsRoute = ApiRatingsRouteImport.update({
  id: '/api/ratings',
  path: '/api/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchHistoryRoute = ApiWatchHistoryRouteImport.update({
  id: '/api/watch-history',
  path: '/api/watch-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchPartyRoute = ApiWatchPartyRouteImport.update({
  id: '/api/watch-party',
  path: '/api/watch-party',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieSlugRoute = MovieSlugRouteImport.update({
  id: '/movie/$slug',
  path: '/movie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchSlugRoute = WatchSlugRouteImport.update({
  id: '/watch/$slug',
  path: '/watch/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVsmovStreamRoute = ApiPublicVsmovStreamRouteImport.update({
  id: '/api/public/vsmov-stream',
  path: '/api/public/vsmov-stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/episode-watcher': typeof ApiEpisodeWatcherRoute
  '/api/ratings': typeof ApiRatingsRoute
  '/api/watch-history': typeof ApiWatchHistoryRoute
  '/api/watch-party': typeof ApiWatchPartyRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/api/public/vsmov-stream': typeof ApiPublicVsmovStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/episode-watcher': typeof ApiEpisodeWatcherRoute
  '/api/ratings': typeof ApiRatingsRoute
  '/api/watch-history': typeof ApiWatchHistoryRoute
  '/api/watch-party': typeof ApiWatchPartyRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/api/public/vsmov-stream': typeof ApiPublicVsmovStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/episode-watcher': typeof ApiEpisodeWatcherRoute
  '/api/ratings': typeof ApiRatingsRoute
  '/api/watch-history': typeof ApiWatchHistoryRoute
  '/api/watch-party': typeof ApiWatchPartyRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/api/public/vsmov-stream': typeof ApiPublicVsmovStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/admin'
    | '/api/episode-watcher'
    | '/api/ratings'
    | '/api/watch-history'
    | '/api/watch-party'
    | '/movie/$slug'
    | '/watch/$slug'
    | '/api/public/vsmov-stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/admin'
    | '/api/episode-watcher'
    | '/api/ratings'
    | '/api/watch-history'
    | '/api/watch-party'
    | '/movie/$slug'
    | '/watch/$slug'
    | '/api/public/vsmov-stream'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/admin'
    | '/api/episode-watcher'
    | '/api/ratings'
    | '/api/watch-history'
    | '/api/watch-party'
    | '/movie/$slug'
    | '/watch/$slug'
    | '/api/public/vsmov-stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiEpisodeWatcherRoute: typeof ApiEpisodeWatcherRoute
  ApiRatingsRoute: typeof ApiRatingsRoute
  ApiWatchHistoryRoute: typeof ApiWatchHistoryRoute
  ApiWatchPartyRoute: typeof ApiWatchPartyRoute
  MovieSlugRoute: typeof MovieSlugRoute
  WatchSlugRoute: typeof WatchSlugRoute
  ApiPublicVsmovStreamRoute: typeof ApiPublicVsmovStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/episode-watcher': {
      id: '/api/episode-watcher'
      path: '/api/episode-watcher'
      fullPath: '/api/episode-watcher'
      preLoaderRoute: typeof ApiEpisodeWatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ratings': {
      id: '/api/ratings'
      path: '/api/ratings'
      fullPath: '/api/ratings'
      preLoaderRoute: typeof ApiRatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watch-history': {
      id: '/api/watch-history'
      path: '/api/watch-history'
      fullPath: '/api/watch-history'
      preLoaderRoute: typeof ApiWatchHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watch-party': {
      id: '/api/watch-party'
      path: '/api/watch-party'
      fullPath: '/api/watch-party'
      preLoaderRoute: typeof ApiWatchPartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$slug': {
      id: '/movie/$slug'
      path: '/movie/$slug'
      fullPath: '/movie/$slug'
      preLoaderRoute: typeof MovieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$slug': {
      id: '/watch/$slug'
      path: '/watch/$slug'
      fullPath: '/watch/$slug'
      preLoaderRoute: typeof WatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vsmov-stream': {
      id: '/api/public/vsmov-stream'
      path: '/api/public/vsmov-stream'
      fullPath: '/api/public/vsmov-stream'
      preLoaderRoute: typeof ApiPublicVsmovStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiEpisodeWatcherRoute: ApiEpisodeWatcherRoute,
  ApiRatingsRoute: ApiRatingsRoute,
  ApiWatchHistoryRoute: ApiWatchHistoryRoute,
  ApiWatchPartyRoute: ApiWatchPartyRoute,
  MovieSlugRoute: MovieSlugRoute,
  WatchSlugRoute: WatchSlugRoute,
  ApiPublicVsmovStreamRoute: ApiPublicVsmovStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
