alter table public.watch_parties add column if not exists join_locked boolean not null default false;
alter table public.movie_comments add column if not exists moderation_status text not null default 'pending';
alter table public.movie_comments add column if not exists moderated_by uuid references auth.users(id) on delete set null;
alter table public.movie_comments add column if not exists moderated_at timestamptz;
alter table public.movie_comments drop constraint if exists movie_comments_moderation_status_check;
alter table public.movie_comments add constraint movie_comments_moderation_status_check
  check (moderation_status in ('pending','approved','hidden'));
create index if not exists movie_comments_moderation_created
  on public.movie_comments(moderation_status,created_at desc);

create table if not exists public.staff_permissions (
  user_id uuid not null references auth.users(id) on delete cascade,
  permission text not null,
  granted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key(user_id,permission)
);
alter table public.staff_permissions drop constraint if exists staff_permissions_permission_check;
alter table public.staff_permissions add constraint staff_permissions_permission_check check (permission in (
  'users.view','users.manage','comments.view','comments.moderate','watch_party.view',
  'watch_party.warn','watch_party.lock','watch_party.close','sources.view'
));

create table if not exists public.watch_party_warnings (
  id uuid primary key default gen_random_uuid(),
  party_id uuid not null references public.watch_parties(id) on delete cascade,
  actor_id uuid not null references auth.users(id) on delete restrict,
  message text not null check(char_length(message) between 1 and 300),
  created_at timestamptz not null default now()
);
create index if not exists watch_party_warnings_rate_limit
  on public.watch_party_warnings(party_id,created_at desc);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references auth.users(id) on delete restrict,
  action text not null,
  target_type text not null,
  target_id text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists admin_audit_log_created on public.admin_audit_log(created_at desc);

alter table public.staff_permissions enable row level security;
alter table public.watch_party_warnings enable row level security;
alter table public.admin_audit_log enable row level security;
revoke all on public.staff_permissions,public.admin_audit_log from anon,authenticated;
revoke insert,update,delete on public.watch_party_warnings from anon,authenticated;
grant select on public.watch_party_warnings to authenticated;
grant all on public.staff_permissions,public.watch_party_warnings,public.admin_audit_log to service_role;

-- All privileged writes route through the server-authorized API.
revoke insert, update, delete on public.watch_parties, public.watch_party_messages, public.watch_party_members from authenticated;

-- Public comments remain readable only while visible; owners retain their own rows.
drop policy if exists "comments readable by everyone" on public.movie_comments;
create policy "visible comments readable" on public.movie_comments for select using (
  moderation_status <> 'hidden' or auth.uid()=user_id
);

drop policy if exists "party members read warnings" on public.watch_party_warnings;
create policy "party members read warnings" on public.watch_party_warnings for select to authenticated using (
  exists(select 1 from public.watch_parties p left join public.watch_party_members m
    on m.party_id=p.id and m.user_id=auth.uid()
    where p.id=watch_party_warnings.party_id and (p.host_id=auth.uid() or m.user_id=auth.uid()))
);

do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime'
    and schemaname='public' and tablename='watch_party_warnings') then
    alter publication supabase_realtime add table public.watch_party_warnings;
  end if;
end $$;
